/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SenderType = IDL.Variant({
  'team' : IDL.Null,
  'visitor' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sentAt' : IDL.Int,
  'senderType' : SenderType,
  'sessionId' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'projectDescription' : IDL.Text,
  'name' : IDL.Text,
  'businessType' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CommentType = IDL.Variant({
  'review' : IDL.Null,
  'request' : IDL.Null,
  'comment' : IDL.Null,
});
export const ProjectComment = IDL.Record({
  'id' : IDL.Nat,
  'clientId' : IDL.Principal,
  'postedAt' : IDL.Int,
  'content' : IDL.Text,
  'projectId' : IDL.Nat,
  'commentType' : CommentType,
});
export const ChatSessionPublic = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'visitorName' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'review' : IDL.Null,
  'pending' : IDL.Null,
  'complete' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ProjectPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'clientId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '__chatMessages' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  '__chatSessions' : IDL.Func([], [IDL.Reserved], ['query']),
  '__chatState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__contactState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__contactSubmissions' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  '__portalState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__projectComments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(ProjectComment)],
      ['query'],
    ),
  '__projects' : IDL.Func([], [IDL.Reserved], ['query']),
  'addClientComment' : IDL.Func(
      [IDL.Nat, IDL.Principal, CommentType, IDL.Text],
      [ProjectComment],
      [],
    ),
  'createChatSession' : IDL.Func([IDL.Text], [ChatSessionPublic], []),
  'createProject' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, ProjectStatus],
      [ProjectPublic],
      [],
    ),
  'getActiveChatSessions' : IDL.Func(
      [],
      [IDL.Vec(ChatSessionPublic)],
      ['query'],
    ),
  'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getClientProjects' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ProjectPublic)],
      ['query'],
    ),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getProjectComments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProjectComment)],
      ['query'],
    ),
  'getProjects' : IDL.Func([], [IDL.Vec(ProjectPublic)], ['query']),
  'sendChatMessage' : IDL.Func(
      [IDL.Text, SenderType, IDL.Text],
      [ChatMessage],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactSubmission],
      [],
    ),
  'updateProjectStatus' : IDL.Func([IDL.Nat, ProjectStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SenderType = IDL.Variant({ 'team' : IDL.Null, 'visitor' : IDL.Null });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sentAt' : IDL.Int,
    'senderType' : SenderType,
    'sessionId' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'projectDescription' : IDL.Text,
    'name' : IDL.Text,
    'businessType' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CommentType = IDL.Variant({
    'review' : IDL.Null,
    'request' : IDL.Null,
    'comment' : IDL.Null,
  });
  const ProjectComment = IDL.Record({
    'id' : IDL.Nat,
    'clientId' : IDL.Principal,
    'postedAt' : IDL.Int,
    'content' : IDL.Text,
    'projectId' : IDL.Nat,
    'commentType' : CommentType,
  });
  const ChatSessionPublic = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'visitorName' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'review' : IDL.Null,
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ProjectPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'clientId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '__chatMessages' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    '__chatSessions' : IDL.Func([], [IDL.Reserved], ['query']),
    '__chatState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__contactState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__contactSubmissions' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    '__portalState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__projectComments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(ProjectComment)],
        ['query'],
      ),
    '__projects' : IDL.Func([], [IDL.Reserved], ['query']),
    'addClientComment' : IDL.Func(
        [IDL.Nat, IDL.Principal, CommentType, IDL.Text],
        [ProjectComment],
        [],
      ),
    'createChatSession' : IDL.Func([IDL.Text], [ChatSessionPublic], []),
    'createProject' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, ProjectStatus],
        [ProjectPublic],
        [],
      ),
    'getActiveChatSessions' : IDL.Func(
        [],
        [IDL.Vec(ChatSessionPublic)],
        ['query'],
      ),
    'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getClientProjects' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ProjectPublic)],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getProjectComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProjectComment)],
        ['query'],
      ),
    'getProjects' : IDL.Func([], [IDL.Vec(ProjectPublic)], ['query']),
    'sendChatMessage' : IDL.Func(
        [IDL.Text, SenderType, IDL.Text],
        [ChatMessage],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactSubmission],
        [],
      ),
    'updateProjectStatus' : IDL.Func([IDL.Nat, ProjectStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };