/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'sentAt' : bigint,
  'senderType' : SenderType,
  'sessionId' : string,
}
export interface ChatSessionPublic {
  'id' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'visitorName' : string,
}
export type CommentType = { 'review' : null } |
  { 'request' : null } |
  { 'comment' : null };
export interface ContactSubmission {
  'id' : bigint,
  'projectDescription' : string,
  'name' : string,
  'businessType' : string,
  'submittedAt' : bigint,
  'email' : string,
  'phone' : string,
}
export interface ProjectComment {
  'id' : bigint,
  'clientId' : Principal,
  'postedAt' : bigint,
  'content' : string,
  'projectId' : bigint,
  'commentType' : CommentType,
}
export interface ProjectPublic {
  'id' : bigint,
  'status' : ProjectStatus,
  'title' : string,
  'clientId' : Principal,
  'createdAt' : bigint,
  'description' : string,
}
export type ProjectStatus = { 'review' : null } |
  { 'pending' : null } |
  { 'complete' : null } |
  { 'inProgress' : null };
export type SenderType = { 'team' : null } |
  { 'visitor' : null };
export interface _SERVICE {
  '__chatMessages' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<ChatMessage>
  >,
  '__chatSessions' : ActorMethod<[], any>,
  '__chatState' : ActorMethod<[], any>,
  '__contactState' : ActorMethod<[], any>,
  '__contactSubmissions' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<ContactSubmission>
  >,
  '__portalState' : ActorMethod<[], any>,
  '__projectComments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<ProjectComment>
  >,
  '__projects' : ActorMethod<[], any>,
  'addClientComment' : ActorMethod<
    [bigint, Principal, CommentType, string],
    ProjectComment
  >,
  'createChatSession' : ActorMethod<[string], ChatSessionPublic>,
  'createProject' : ActorMethod<
    [Principal, string, string, ProjectStatus],
    ProjectPublic
  >,
  'getActiveChatSessions' : ActorMethod<[], Array<ChatSessionPublic>>,
  'getChatMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getClientProjects' : ActorMethod<[Principal], Array<ProjectPublic>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getProjectComments' : ActorMethod<[bigint], Array<ProjectComment>>,
  'getProjects' : ActorMethod<[], Array<ProjectPublic>>,
  'sendChatMessage' : ActorMethod<[string, SenderType, string], ChatMessage>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    ContactSubmission
  >,
  'updateProjectStatus' : ActorMethod<[bigint, ProjectStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];