/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProjectComment {
    id: bigint;
    clientId: Principal;
    postedAt: bigint;
    content: string;
    projectId: bigint;
    commentType: CommentType;
}
export interface ChatSessionPublic {
    id: string;
    createdAt: bigint;
    isActive: boolean;
    visitorName: string;
}
export interface ProjectPublic {
    id: bigint;
    status: ProjectStatus;
    title: string;
    clientId: Principal;
    createdAt: bigint;
    description: string;
}
export interface ContactSubmission {
    id: bigint;
    projectDescription: string;
    name: string;
    businessType: string;
    submittedAt: bigint;
    email: string;
    phone: string;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    sentAt: bigint;
    senderType: SenderType;
    sessionId: string;
}
export enum CommentType {
    review = "review",
    request = "request",
    comment = "comment"
}
export enum ProjectStatus {
    review = "review",
    pending = "pending",
    complete = "complete",
    inProgress = "inProgress"
}
export enum SenderType {
    team = "team",
    visitor = "visitor"
}
export interface backendInterface {
    __chatMessages(io: bigint | null, count: bigint | null): Promise<Array<ChatMessage>>;
    __chatSessions(): Promise<any>;
    __chatState(): Promise<any>;
    __contactState(): Promise<any>;
    __contactSubmissions(io: bigint | null, count: bigint | null): Promise<Array<ContactSubmission>>;
    __portalState(): Promise<any>;
    __projectComments(io: bigint | null, count: bigint | null): Promise<Array<ProjectComment>>;
    __projects(): Promise<any>;
    addClientComment(projectId: bigint, clientId: Principal, commentType: CommentType, content: string): Promise<ProjectComment>;
    createChatSession(visitorName: string): Promise<ChatSessionPublic>;
    createProject(clientId: Principal, title: string, description: string, status: ProjectStatus): Promise<ProjectPublic>;
    getActiveChatSessions(): Promise<Array<ChatSessionPublic>>;
    getChatMessages(sessionId: string): Promise<Array<ChatMessage>>;
    getClientProjects(clientId: Principal): Promise<Array<ProjectPublic>>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getProjectComments(projectId: bigint): Promise<Array<ProjectComment>>;
    getProjects(): Promise<Array<ProjectPublic>>;
    sendChatMessage(sessionId: string, senderType: SenderType, content: string): Promise<ChatMessage>;
    submitContactForm(name: string, email: string, phone: string, businessType: string, projectDescription: string): Promise<ContactSubmission>;
    updateProjectStatus(projectId: bigint, status: ProjectStatus): Promise<boolean>;
}
import type { ChatMessage as _ChatMessage, CommentType as _CommentType, ProjectComment as _ProjectComment, ProjectPublic as _ProjectPublic, ProjectStatus as _ProjectStatus, SenderType as _SenderType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __chatMessages(arg0: bigint | null, arg1: bigint | null): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.__chatMessages(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__chatMessages(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __chatSessions(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__chatSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__chatSessions();
            return result;
        }
    }
    async __chatState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__chatState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__chatState();
            return result;
        }
    }
    async __contactState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__contactState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__contactState();
            return result;
        }
    }
    async __contactSubmissions(arg0: bigint | null, arg1: bigint | null): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.__contactSubmissions(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__contactSubmissions(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __portalState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__portalState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__portalState();
            return result;
        }
    }
    async __projectComments(arg0: bigint | null, arg1: bigint | null): Promise<Array<ProjectComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.__projectComments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__projectComments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async __projects(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__projects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__projects();
            return result;
        }
    }
    async addClientComment(arg0: bigint, arg1: Principal, arg2: CommentType, arg3: string): Promise<ProjectComment> {
        if (this.processError) {
            try {
                const result = await this.actor.addClientComment(arg0, arg1, to_candid_CommentType_n12(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_ProjectComment_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClientComment(arg0, arg1, to_candid_CommentType_n12(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_ProjectComment_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createChatSession(arg0: string): Promise<ChatSessionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatSession(arg0);
            return result;
        }
    }
    async createProject(arg0: Principal, arg1: string, arg2: string, arg3: ProjectStatus): Promise<ProjectPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2, to_candid_ProjectStatus_n14(this._uploadFile, this._downloadFile, arg3));
                return from_candid_ProjectPublic_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2, to_candid_ProjectStatus_n14(this._uploadFile, this._downloadFile, arg3));
            return from_candid_ProjectPublic_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveChatSessions(): Promise<Array<ChatSessionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveChatSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveChatSessions();
            return result;
        }
    }
    async getChatMessages(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientProjects(arg0: Principal): Promise<Array<ProjectPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientProjects(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientProjects(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getProjectComments(arg0: bigint): Promise<Array<ProjectComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectComments(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectComments(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<ProjectPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendChatMessage(arg0: string, arg1: SenderType, arg2: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, to_candid_SenderType_n21(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_ChatMessage_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, to_candid_SenderType_n21(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_ChatMessage_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateProjectStatus(arg0: bigint, arg1: ProjectStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectStatus(arg0, to_candid_ProjectStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectStatus(arg0, to_candid_ProjectStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ChatMessage_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_CommentType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommentType): CommentType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectComment_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectComment): ProjectComment {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectPublic_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectPublic): ProjectPublic {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SenderType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SenderType): SenderType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    title: string;
    clientId: Principal;
    createdAt: bigint;
    description: string;
}): {
    id: bigint;
    status: ProjectStatus;
    title: string;
    clientId: Principal;
    createdAt: bigint;
    description: string;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n18(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: value.clientId,
        createdAt: value.createdAt,
        description: value.description
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    sentAt: bigint;
    senderType: _SenderType;
    sessionId: string;
}): {
    id: bigint;
    content: string;
    sentAt: bigint;
    senderType: SenderType;
    sessionId: string;
} {
    return {
        id: value.id,
        content: value.content,
        sentAt: value.sentAt,
        senderType: from_candid_SenderType_n5(_uploadFile, _downloadFile, value.senderType),
        sessionId: value.sessionId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    clientId: Principal;
    postedAt: bigint;
    content: string;
    projectId: bigint;
    commentType: _CommentType;
}): {
    id: bigint;
    clientId: Principal;
    postedAt: bigint;
    content: string;
    projectId: bigint;
    commentType: CommentType;
} {
    return {
        id: value.id,
        clientId: value.clientId,
        postedAt: value.postedAt,
        content: value.content,
        projectId: value.projectId,
        commentType: from_candid_CommentType_n10(_uploadFile, _downloadFile, value.commentType)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    review: null;
} | {
    request: null;
} | {
    comment: null;
}): CommentType {
    return "review" in value ? CommentType.review : "request" in value ? CommentType.request : "comment" in value ? CommentType.comment : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    review: null;
} | {
    pending: null;
} | {
    complete: null;
} | {
    inProgress: null;
}): ProjectStatus {
    return "review" in value ? ProjectStatus.review : "pending" in value ? ProjectStatus.pending : "complete" in value ? ProjectStatus.complete : "inProgress" in value ? ProjectStatus.inProgress : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    team: null;
} | {
    visitor: null;
}): SenderType {
    return "team" in value ? SenderType.team : "visitor" in value ? SenderType.visitor : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectPublic>): Array<ProjectPublic> {
    return value.map((x)=>from_candid_ProjectPublic_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectComment>): Array<ProjectComment> {
    return value.map((x)=>from_candid_ProjectComment_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CommentType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommentType): _CommentType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_SenderType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SenderType): _SenderType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommentType): {
    review: null;
} | {
    request: null;
} | {
    comment: null;
} {
    return value == CommentType.review ? {
        review: null
    } : value == CommentType.request ? {
        request: null
    } : value == CommentType.comment ? {
        comment: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    review: null;
} | {
    pending: null;
} | {
    complete: null;
} | {
    inProgress: null;
} {
    return value == ProjectStatus.review ? {
        review: null
    } : value == ProjectStatus.pending ? {
        pending: null
    } : value == ProjectStatus.complete ? {
        complete: null
    } : value == ProjectStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SenderType): {
    team: null;
} | {
    visitor: null;
} {
    return value == SenderType.team ? {
        team: null
    } : value == SenderType.visitor ? {
        visitor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
